# Generated by Django 4.2.4 on 2023-08-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('course_name', models.TextField()),
                ('document_link', models.TextField()),
                ('code', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='images/')),
                ('author', models.TextField()),
                ('tag', models.TextField()),
            ],
        ),
    ]
